services:
  stable-diffusion:
    build: .
    container_name: stable-diffusion-webui
    ports:
      - "7860:7860"
    volumes:
      - ./models:/stable-diffusion-webui/models/Stable-diffusion
    restart: unless-stopped
    command:
      [
        "python",
        "launch.py",
        "--listen",
        "--port=7860",
        "--skip-torch-cuda-test",
        "--use-cpu",
        "all",
        "--no-half",
      ]
